export const list = [
    {
        title: "Title 1",
        contents: [
            "Quiz 1",
            "Quiz 2",
            "Quiz 3",
            "Quiz 4",
            "Quiz 5",
            "Quiz 6",
            "Quiz 7",
            "Quiz 8",
            "Quiz 9",
            "Quiz 10",
        ],
    },
    {
        title: "Title 2",
        contents: [
            "Quiz 1",
            "Quiz 2",
            "Quiz 3",
            "Quiz 4",
            "Quiz 5",
            "Quiz 6",
            "Quiz 7",
            "Quiz 8",
            "Quiz 9",
            "Quiz 10",
        ],
    },
    {
        title: "Title 3",
        contents: [
            "Quiz 1",
            "Quiz 2",
            "Quiz 3",
            "Quiz 4",
            "Quiz 5",
            "Quiz 6",
            "Quiz 7",
            "Quiz 8",
            "Quiz 9",
            "Quiz 10",
        ],
    },
    {
        title: "Title 4",
        contents: [
            "Quiz 1",
            "Quiz 2",
            "Quiz 3",
            "Quiz 4",
            "Quiz 5",
            "Quiz 6",
            "Quiz 7",
            "Quiz 8",
            "Quiz 9",
            "Quiz 10",
        ],
    },
    {
        title: "Title 5",
        contents: [
            "Quiz 1",
            "Quiz 2",
            "Quiz 3",
            "Quiz 4",
            "Quiz 5",
            "Quiz 6",
            "Quiz 7",
            "Quiz 8",
            "Quiz 9",
            "Quiz 10",
        ],
    },
]
